name: 构建阿里云容器镜像

on: push

jobs:
  test:
    name: CheckOut
    runs-on: ubuntu-latest
    steps:
      - name: "复制文件"
        uses: actions/checkout@v1
      - name: "列出文件"
        run: ls
      - name: "打包推送镜像"
        run: |
          docker login --username=${{ secrets.ALIYUN_DOCKER_NAME }} registry.cn-hongkong.aliyuncs.com --password=${{ secrets.ALIYUN_DOCKER_PASS }}
